### PR TITLE
Fix netlist creation when code contains concurrent assertions

### LINKED ISSUE #1002: Assertion 'T::isKind(kind)' failed
**Describe the bug**
A full SoC run passes with `slang` but when it is ran with `slang-netlist` (no additional flags), it fails with:

```
Assertion 'T::isKind(kind)' failed
  in file /home/udif/git2/slang/tools/netlist/../../include/slang/ast/Statements.h, line 238
  function: const T& slang::ast::Statement::as() const [with T = slang::ast::TimedStatement]
```
.

**To Reproduce**
At the moment that would be hard, as it is the result of proprietary SoC full tree run.

**Additional context**
I wish I could give out more information, but if the assertion could provide a `SourceLocation` I might be able to reduce it to an MRE.

### PR DESCRIPTION
**Pull request by udif**
This is the beginning of a PR to fix #1002 .
It works for a simple testcase that fails otherwise, but I still see different failures (DirectedGraph issue, might be unrelated) when reading larger examples such as those provided in #1002, so I don't think it is ready yet, but it's a start and it can be reviewed.

### CODE REVIEW

File: tools/netlist/include/NetlistVisitor.h [hunk 1]
```diff
@@ -605,6 +605,14 @@ class NetlistVisitor : public ast::ASTVisitor<NetlistVisitor, true, false> {
         ast::EdgeKind edgeKind = ast::EdgeKind::None;
         if (symbol.procedureKind == ast::ProceduralBlockKind::AlwaysFF ||
             symbol.procedureKind == ast::ProceduralBlockKind::Always) {
+            // auto& body = symbol.getBody();
```
Comment (MikePopoloski) [inline tools/netlist/include/NetlistVisitor.h:608]: Remove extraneous commented out line.

File: tools/netlist/include/NetlistVisitor.h [hunk 2]
```diff
@@ -605,6 +605,14 @@ class NetlistVisitor : public ast::ASTVisitor<NetlistVisitor, true, false> {
...
+            if (symbol.getBody().kind == ast::StatementKind::Block) {
```
Comment (MikePopoloski) [inline tools/netlist/include/NetlistVisitor.h:609]: Do you want to just ignore all statements that aren't a TimedStatement? Otherwise you'll still crash below.

File: tools/netlist/tests/NameTests.cpp [hunk 3]
```diff
@@ -55,3 +55,40 @@ endmodule
     auto netlist = createNetlist(compilation);
     CHECK(netlist.numNodes() > 0);
 }
+
+TEST_CASE("Ignore concurrent assertions") {
+    // Test that unused modules are not visited by the netlist builder.
```
Comment (MikePopoloski) [inline tools/netlist/tests/NameTests.cpp:60]: Comment is copy pasta from the previous test case.

File: tools/netlist/include/NetlistVisitor.h (hunk 2 above)
Comment (udif) [reply tools/netlist/include/NetlistVisitor.h:609]: As I'm not sure what elements can be nested in the AST, I would rather get a fault during debugging rather than silently skipping netlist elements by mistake.
At the moment, I'm explicitly checking for those AST elements I know I need to skip, in this case a concurrent assertion under a sequential block.
Can concurrent assertions be found elsewhere?

File: tools/netlist/tests/NameTests.cpp (hunk 3 above)
Comment (udif) [reply tools/netlist/tests/NameTests.cpp:60]: fixed locally, will be pushed when I have more meaningful changes later.

**Comment by MikePopoloski** [comment]
What's the status of this PR?

**Comment by udif** [comment]
I apologize, after being blocked by #1007 I forgot about this, thanks for reminding me.
I will have to rebase it on the new Netlist code. It will take me a few more days.

**Comment by udif** [comment]
I think it is OK now.
