### PR TITLE
Reflect more complex local parameters

### LINKED ISSUE #825: Wrong index variant on slang-reflect
The following construct will cause a:
```
terminate called after throwing an instance of 'std::bad_variant_access'
  what():  std::get: wrong index for variant
Aborted (core dumped)
```

the construct:

```systemverilog
localparam [CORE_ID_BITS - 1:0] CORE_ID_0 [pkg::NR_CORES] = '{2, 3, 0, 0, 0}; 
localparam [CORE_ID_BITS - 1:0] CORE_ID_1 [pkg::NR_CORES] = '{4, 5, 0, 0, 0}; 
localparam [CORE_ID_BITS - 1:0] CORE_ID [2][pkg::NR_CORES] /* verilator public */ = '{CORE_ID_0, CORE_ID_1};  
```

### PR DESCRIPTION
**Pull request by Sustrak**
With this commit slang-reflect is able to reflect more complex local parameters. Also, it will throw an error if it doesn't know how to reflect the parameter instead of crashing.

Fixes #825

### CODE REVIEW

File: tools/reflect/src/SvLocalParam.cpp [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+void SvLocalParam::toCpp(HppFile& hppFile, std::string_view, const SvAliases&, bool) const {
+    std::string parameterName = isCppReserved(parameter.name) ? fmt::format("_{}", parameter.name)
+                                                              : std::string(parameter.name);
+    if (parameter.getValue().isUnpacked()) {
+        std::vector<std::vector<uint64_t>> unpackedArrays;
+        uint64_t biggestSize = 0;
+        SLANG_TRY {
+            unwrapUnpackedArray(parameter.getValue().elements(), unpackedArrays, biggestSize);
+        }
+        SLANG_CATCH(const std::runtime_error& error) {
```
Comment (MikePopoloski) [inline tools/reflect/src/SvLocalParam.cpp:36]: The exception object gets removed when exceptions are disabled, so you then can't refer to it in the format() message below. You would need to put that call between a `#if __cpp_exceptions` so that the no-exception build will pass.

Comment (Sustrak) [reply tools/reflect/src/SvLocalParam.cpp:36]: Right, done so in the last commit :+1:
